# -*- coding: utf-8 -*-
"""HWIH replication pipeline: step 03 — emit .tex tables + number macros from results.csv.
All manuscript numbers flow through here; nothing is hand-copied."""

# Replication-package paths
from pathlib import Path as _ReplicationPath
import os as _ReplicationOS
_REP_PROJECT = _ReplicationPath(__file__).resolve().parents[1]
_REP_PACKAGE = _REP_PROJECT.parent
_REP_RESTRICTED = _REP_PACKAGE / 'restricted_data'
_REP_JUDGMENTS = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_JUDGMENT_ARCHIVE', _REP_RESTRICTED / 'judgment_archive'))
_REP_CASE_ARCHIVE = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_CASE_LEVEL_ARCHIVE', _REP_RESTRICTED / 'case_level_archive.parquet'))
_REP_MORTALITY = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_CDC_SOURCE_ROOT', _REP_RESTRICTED / 'mortality_volumes'))
_REP_REGISTRY = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_REGISTRY_ROOT', _REP_RESTRICTED / 'firm_registry'))
_REP_BAIDU = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_BAIDU_ROOT', _REP_RESTRICTED / 'baidu'))
_REP_INTERVIEWS = _ReplicationPath(_ReplicationOS.environ.get(
    'HWIH_INTERVIEWS_ROOT', _REP_RESTRICTED / 'interviews'))
import pandas as pd, numpy as np, os

OUTD = str(_REP_PROJECT / "output")
TABD = f"{OUTD}/tables"
os.makedirs(TABD, exist_ok=True)
r = pd.read_csv(f"{OUTD}/results.csv").set_index(["tag", "coef"])
es = pd.read_csv(f"{OUTD}/eventstudy.csv")
flow = pd.read_csv(str(_REP_PROJECT / 'data' / 'sample_flow.csv').replace('\\', '/'))

def cell(tag, coef="px"):
    row = r.loc[(tag, coef)]
    e, se, p, wp = row["est"], row["se"], row["p"], row["wild_p"]
    wtxt = f"{wp:.3f}" if not np.isnan(wp) else "--"
    return f"{e:.4f} & ({se:.4f}) & {wtxt}", row["n"]

# ---------------------------------------------------------------- numbers.tex
mac = []
def num(name, val): mac.append(f"\\newcommand{{\\{name}}}{{{val}}}")
num("NRawArchive", f"{int(flow.iloc[0]['n']):,}")
num("NMainWindow", f"{int(flow[flow['step'].str.startswith('S3')]['n'].iloc[0]):,}")
num("NAnalysisCases", f"{int(flow[flow['step'].str.startswith('S4')]['n'].iloc[0]):,}")
num("NMechCases", f"{int(flow[flow['step'].str.startswith('S5')]['n'].iloc[0]):,}")
num("NPanelCells", f"{int(flow[flow['step'].str.startswith('S6b')]['n'].iloc[0]):,}")
for tag, macro in [("B_market_dose_y_backstop", "CoefMarketBackstop"),
                   ("B_violence_dose_y_backstop", "CoefViolenceBackstop"),
                   ("A_triplediff_y_backstop", "CoefTDBackstop"),
                   ("B_market_dose_y_rel_failure", "CoefMarketRelFail"),
                   ("B_market_dose_logn", "CoefMarketLogN")]:
    c = "pxm" if tag.startswith("A_") else "px"
    row = r.loc[(tag, c)]
    num(macro, f"{row['est']:.3f}")
    num(macro + "SE", f"{row['se']:.3f}")
    num(macro + "P", f"{row['p']:.3f}")
    num(macro + "WildP", f"{row['wild_p']:.3f}" if not np.isnan(row['wild_p']) else "--")
pre = es.groupby("outcome")["pretrend_p"].first()
num("PretrendBackstop", f"{pre['y_backstop']:.3f}")
num("PretrendRelFail", f"{pre['y_rel_failure']:.3f}")
num("PretrendFormalization", f"{pre['y_formalization']:.3f}")
jr = r.loc[("D_joint_stacked", "px_relfail")]
num("JointWaldP", jr["fml"].split("=")[1][:6])
with open(f"{TABD}/numbers.tex", "w", encoding="utf-8") as f:
    f.write("% auto-generated by 03_tables.py — do not edit\n" + "\n".join(mac) + "\n")

# ------------------------------------------------------------ tab_main.tex
rows_a = [("Hard-backstop usage", "A_triplediff_y_backstop"),
          ("Relational-transaction language", "A_triplediff_y_relational"),
          ("Relational failure visible", "A_triplediff_y_rel_failure"),
          ("Ex-ante formalization", "A_triplediff_y_formalization")]
rows_b = [("Hard-backstop usage", "B_market_dose_y_backstop"),
          ("Relational-transaction language", "B_market_dose_y_relational"),
          ("Relational failure visible", "B_market_dose_y_rel_failure"),
          ("Ex-ante formalization", "B_market_dose_y_formalization"),
          ("Log case count", "B_market_dose_logn")]
L = [r"\begin{tabular}{lccc}", r"\toprule",
     r"Outcome & Coefficient & (CRV1 SE) & Wild-score $p$ \\ \midrule",
     r"\multicolumn{4}{l}{\emph{Panel A. Triple difference: market crimes vs.\ traffic placebo,}} \\",
     r"\multicolumn{4}{l}{\emph{\quad Post$\times$Exposure$\times$Market}} \\[2pt]"]
for lab, tag in rows_a:
    c, n = cell(tag, "pxm"); L.append(f"{lab} & {c} \\\\")
L += [r"\midrule", r"\multicolumn{4}{l}{\emph{Panel B. Within market crimes: Post$\times$Exposure (dose response)}} \\[2pt]"]
for lab, tag in rows_b:
    c, n = cell(tag, "px"); L.append(f"{lab} & {c} \\\\")
nA = int(r.loc[('A_triplediff_y_backstop','pxm')]['n']); nB = int(r.loc[('B_market_dose_y_backstop','px')]['n'])
L += [r"\midrule", f"Cells (Panel A / Panel B) & \\multicolumn{{3}}{{c}}{{{nA:,} / {nB:,}}} \\\\",
      r"Fixed effects & \multicolumn{3}{c}{pref$\times$group, prov$\times$month, group$\times$month} \\",
      r"\bottomrule", r"\end{tabular}"]
open(f"{TABD}/tab_main.tex", "w", encoding="utf-8").write("\n".join(L) + "\n")

# ------------------------------------------------------- tab_mechanism.tex
L = [r"\begin{tabular}{lccc}", r"\toprule",
     r" & Coefficient & (SE) & Wild-score $p$ \\ \midrule"]
c, _ = cell("B_violence_dose_y_backstop"); L.append(f"Violence margin (intentional-injury cells) & {c} \\\\")
bs = r.loc[("D_joint_stacked", "px_backstop")]; rf = r.loc[("D_joint_stacked", "px_relfail")]
L.append(f"Stacked: backstop equation & {bs['est']:.4f} & ({bs['se']:.4f}) & -- \\\\")
L.append(f"Stacked: relational-failure equation & {rf['est']:.4f} & ({rf['se']:.4f}) & -- \\\\")
L += [r"\midrule", f"Joint Wald $p$ (co-movement) & \\multicolumn{{3}}{{c}}{{{jr['fml'].split('=')[1][:6]}}} \\\\",
      r"\bottomrule", r"\end{tabular}"]
open(f"{TABD}/tab_mechanism.tex", "w", encoding="utf-8").write("\n".join(L) + "\n")

# ------------------------------------------------------- tab_robust.tex
rows_e = [("Theft placebo: hard backstop (DDD)", "E_theftplacebo_y_backstop", "pxm"),
          ("Theft placebo: relational failure (DDD)", "E_theftplacebo_y_rel_failure", "pxm"),
          ("Pre-2020 window: hard backstop", "E_pre2020_y_backstop", "px"),
          ("Pre-2020 window: relational failure", "E_pre2020_y_rel_failure", "px"),
          ("Exposure component: direct-crime share", "E_expcomp_direct_share_z", "pxc"),
          ("Exposure component: coercive text rate", "E_expcomp_coercive_rate_z", "pxc")]
L = [r"\begin{tabular}{lccc}", r"\toprule",
     r"Specification & Coefficient & (SE) & Wild-score $p$ \\ \midrule"]
for lab, tag, cf in rows_e:
    c, _ = cell(tag, cf); L.append(f"{lab} & {c} \\\\")
L += [r"\bottomrule", r"\end{tabular}"]
open(f"{TABD}/tab_robust.tex", "w", encoding="utf-8").write("\n".join(L) + "\n")

# ------------------------------------------------------- tab_eventstudy.tex
L = [r"\begin{tabular}{lccc}", r"\toprule",
     r"Event-time bin (months) & Backstop & Rel.\ failure & Formalization \\ \midrule"]
piv = es.pivot_table(index=["bin_lo", "bin_hi"], columns="outcome", values=["est", "se"])
for (lo, hi), row in piv.iterrows():
    def fmt(y):
        e, s = row[("est", y)], row[("se", y)]
        return f"{e:.4f} ({s:.4f})"
    ref = r" (ref.)" if (lo, hi) == (-6, -1) else ""
    L.append(f"{{[{lo},{hi}]}}{ref} & {fmt('y_backstop')} & {fmt('y_rel_failure')} & {fmt('y_formalization')} \\\\")
L += [r"\midrule",
      f"Pretrend joint $p$ & {pre['y_backstop']:.3f} & {pre['y_rel_failure']:.3f} & {pre['y_formalization']:.3f} \\\\",
      r"\bottomrule", r"\end{tabular}"]
open(f"{TABD}/tab_eventstudy.tex", "w", encoding="utf-8").write("\n".join(L) + "\n")

# ------------------------------------------------------- tab_sampleflow.tex
L = [r"\begin{tabular}{lr}", r"\toprule", r"Step & Judgments \\ \midrule"]
for _, row in flow.iterrows():
    L.append(f"{row['step'].replace('_',' ')} & {int(row['n']):,} \\\\")
L += [r"\bottomrule", r"\end{tabular}"]
open(f"{TABD}/tab_sampleflow.tex", "w", encoding="utf-8").write("\n".join(L) + "\n")
print("tables written:", os.listdir(TABD))
